### PR TITLE
Adding a GPL V2 license file.

### PR DESCRIPTION
**Pull request by russ**
References issue #17

### CODE REVIEW

**Comment by russ** [comment]
Thanks for the note about this. I've opened a pull request to get feedback from the other contributors to the app.

**Comment by brianvh** [comment]
While I don't feel super-strong about this, I will say that the GPL, and it's variants, aren't among my favorite OS licenses. I'm almost always tend to prefer the MIT or Apache licenses, or even the BSD license. But, that's likely my Ivy League prejudices showing through. :)

If the group prefers GPL, that's fine with me.

**Comment by russ** [comment]
@brianvh Would you mind explaining why? I'm interested in the differences and consequences.

**Comment by brianvh** [comment]
It's mostly about the viral nature of the GPL. I prefer open source software that is sharable/consumable, but without side effects on the code into which the sharing/consuming happens. That can't ever be the case with GPL licensed  code.

Also, the forced nature of re-sharing that's built into the GPL has always felt incredibly heavy-handed to me. Those involved with open source should want to contribute as much, if not more than, they consume. We shouldn't need to force people to into some form of code give-back.

The MIT license was practically developed as a direct response to these less than positive aspects of the GPL. It's been my OS license of choice, since I first formed an opinion about this stuff back in the early '90s. :)

**Comment by russ** [comment]
That's all the argument I needed. Sounds like a better option to me. I'm going to roll with it.

**Pull request merged**
